services:
  db:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=/run/secrets/db_password
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
      - ./initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 3
    secrets:
      - db_password
      - db_app_username
      - db_app_password
      - db_host
  app:
    image : imadslm/collab_api-app:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DB_DATABASE=${DB_APP_DATABASE}
      - DB_USERNAME=${DB_APP_USERNAME}
      - DB_PASSWORD=${DB_APP_PASSWORD}
      - DB_HOST=${DB_APP_HOST}
    # healthcheck:
    #   test: curl --fail http://localhost:3000/ || exit 1
    #   interval: 40s
    #   timeout: 30s
    #   retries: 3
    #   start_period: 60s
    depends_on:
      db:
        condition: service_healthy
        restart: true
    secrets:
      - db_password
      - db_app_username
      - db_app_password
      - db_host

secrets:
  db_password:
    file: ./secrets/db_password.txt
  db_app_username:
    file: ./secrets/db_app_username.txt
  db_app_password:
    file: ./secrets/db_app_password.txt
  db_host:
    file: ./secrets/db_host.txt
volumes:
  db_data: