apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yaml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yaml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: app
    spec:
      containers:
        - env:
            - name: DB_DATABASE
            - name: DB_HOST
            - name: DB_PASSWORD
              value: /run/secrets/app-password
            - name: DB_USERNAME
              value: /run/secrets/app-user
          image: imadslm/collab_api-app:latest
          livenessProbe:
            exec:
              command:
                - curl --fail http://localhost:3000/ || exit 1
            failureThreshold: 3
            initialDelaySeconds: 60
            periodSeconds: 40
            timeoutSeconds: 30
          name: app
          ports:
            - containerPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /run/secrets
              name: db-password
              subPath: db-password
            - mountPath: /run/secrets
              name: app-user
              subPath: app-user
            - mountPath: /run/secrets
              name: app-password
              subPath: app-password
      restartPolicy: Always
      volumes:
        - name: db-password
          secret:
            items:
              - key: db-password
                path: db-password
            secretName: db-password
        - name: app-user
          secret:
            items:
              - key: app-user
                path: app-user
            secretName: app-user
        - name: app-password
          secret:
            items:
              - key: app-password
                path: app-password
            secretName: app-password
