apiVersion: v1
data:
  initdb.sql: |-
    CREATE DATABASE collabdb;

    CREATE USER 'USERNAME_PLACEHOLDER' IDENTIFIED BY 'PASSWORD_PLACEHOLDER';

    -- L'utilisateur n'a accès qu'à la BDD
    GRANT SELECT, INSERT, UPDATE, DELETE ON collabdb.* TO 'USERNAME_PLACEHOLDER'@'%';

    -- Utilisation de la base de données 'collabdb'
    USE collabdb;
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: db
  name: db-cm1
